# Generated by Django 5.1.5 on 2025-01-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0003_url_user_alter_url_clicks_alter_url_original_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='url',
            name='last_user',
            field=models.TextField(null=True),
        ),
    ]
