name: Deploy to EC2

on:
  push:
    branches:
      - main
	workflow_run:
    	workflows: ["Run tests", "Run ruff"]  # Nombres de los workflows
    	branches: [main]
    	types: [completed]  # Se dispara cuando los workflows terminan

jobs:
  deploy:
    needs: [ruff, tests]
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}  # IP pública
          EC2_USER: ubuntu
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}  # Contenido del archivo .pem
        run: |
          echo "$EC2_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            cd ~/Ejercicio2
            git pull origin main
            pip3 install -r requirements.txt
            python3 manage.py migrate
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF
          rm private_key.pem