name: Run tests

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
jobs:
    tests:
        runs-on: ubuntu-latest
        environment: CI
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up python
              uses: actions/setup-python@v4
              with:
                    python-version: 3.8
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            - name: Run tests
              run: |
                    pytest